### ISSUE TITLE
Improve comparison with HyperLogLog implementation of Redis

### ISSUE THREAD

**Issue by oertl** [wangyi-fudan/wyset#1]
The current comparison with the HyperLogLog (HLL) implementation of Redis is not fair. Redis HLL is able to count up to 2^64 different elements, while wyHLL reaches its limits at about 2^15 which makes it unsuitable for practical applications.

**Comment by wangyi-fudan** [comment]
Dear oertl:
   nice to hear from you!
   wyHLL is not limited to 2^15. For example, the main figure in readme scales to 10^7. And we can do even more.
   Although wyHLL uses 3 bits per slot, it is not limited to 2^7 per register. But rather a wide dynamic range.
   conventional HLL  uses the number of leading zeros in binary format to assign the register value. But we conceptually can divide that number by 2 or 3 or 4... Thus 3-bit register can represent a much larger range.
  In wyHLL, the user sets a "capacity" parameter to the counter. We are sure to count that capacity even it is large (e.g. 2^32).
  The only loss, when set a too large capacity, is the loss of accuracy. For most applications, we don't need that large capacity.

**Comment by oertl** [comment]
Thanks, got it. I misinterpreted the scale in the figure. I thought the max is 8000 instead of 10^8.000. As I understand now, wyHLL corresponds to the Generalized HyperLogLog with a base larger than 2, for which it is known that you can achieve better space efficiencies. You might be interested in this paper https://arxiv.org/pdf/2007.08051.pdf by Seth Pettie.

**Comment by oertl** [comment]
For large capacities, you will need values of `p` that correspond to Generalized HyperLogLog with larger bases. For those cases, it might be necessary to introduce offsets as described in the mentioned paper, to make the variance more homogeneous.

**Comment by wangyi-fudan** [comment]
thanks!
